[logs]
level = 30

[http]
listen = 0.0.0.0:1234

[backend]
allowall = false
secret = RECORDING_SECRET_PLACEHOLDER
backends = backend-1
skipverify = false
maxmessagesize = 1024
videowidth = 1920
videoheight = 1080
directory = /tmp

[backend-1]
url = https://nxdev.defensys.seg.br
secret = RECORDING_SECRET_PLACEHOLDER
skipverify = false

[signaling]
signalings = signaling-1

[signaling-1]
url = ws://shared-signaling:8080
internalsecret = SIGNALING_INTERNAL_SECRET_PLACEHOLDER

[ffmpeg]
extensionaudio = .ogg
extensionvideo = .webm

[recording]
browser = firefox
driverPath = /usr/bin/geckodriver
browserPath = /usr/bin/firefox
